version: '3'

services:
  monitoring-device:
    build:
      context: ../
      dockerfile: docker/dockerfile.source
    container_name: monitoring_device
    ports:
      - "3000:3000"
      - "3001:3001"
    volumes:
      - ../data:/usr/src/app/data
    networks:
      - app-network
    restart: always

networks:
  app-network:
    driver: bridge
